name = 'vidrieraencasa-backend'
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "vidrieraencasa-db"
database_id = "581b05d5-c10a-45df-8491-a2ad8d703b49"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "vidrieraencasa"

[vars]
APP_URL = "https://vidrieraencasa.com"
CDN_URL = "https://cdn.vidrieraencasa.com"
MERCADOPAGO_WEBHOOK_URL = "https://api.vidrieraencasa.com"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true
